package dk.ku.di.dms.vms.modb.common.schema.meta;

import dk.ku.di.dms.vms.modb.common.constraint.ConstraintReference;
import dk.ku.di.dms.vms.modb.common.constraint.ExternalVmsForeignKeyReference;
import dk.ku.di.dms.vms.modb.common.constraint.ForeignKeyReference;
import dk.ku.di.dms.vms.modb.common.type.DataType;

/**
 * High-level description of the data model.
 * Different from the logical schema, which is more internal to the DBMS
 * The <code>VmsSchema</code> record describes the schema of VmsTable.
 * Used to share VMs context to coordinator.
 * Some fields are not necessarily needs being propagated, such as pkAutoGenerated
 * and constraintReferences, but this is only propagated once, so not much overhead...
 */
public class VmsTableSchema {

    public final String tableName;

    // identification of columns that form the primary key. all tables must have a primary key
    public final int[] primaryKeyColumns;

    public final boolean pkAutoGenerated;

    // the name of the columns
    public final String[] columnNames;

    // the data types of the columns
    public final DataType[] columnDataTypes;

    /**
     * Foreign key references within the same virtual microservice application
     */
    public final ForeignKeyReference[] foreignKeyReferences;

    /**
     * Constraints, referred by column position
     */
    public final ConstraintReference[] constraintReferences;

    /**
     * External foreign key reference
     */
    public final ExternalVmsForeignKeyReference[] externalForeignKeyReferences;

    public VmsTableSchema(String tableName, int[] primaryKeyColumns, boolean pkAutoGenerated,
                          String[] columnNames, DataType[] columnDataTypes,
                          ForeignKeyReference[] foreignKeyReferences, ConstraintReference[] constraintReferences,
                          ExternalVmsForeignKeyReference[] externalForeignKeyReferences) {
        this.tableName = tableName;
        this.primaryKeyColumns = primaryKeyColumns;
        this.pkAutoGenerated = pkAutoGenerated;
        this.columnNames = columnNames;
        this.columnDataTypes = columnDataTypes;
        this.foreignKeyReferences = foreignKeyReferences;
        this.constraintReferences = constraintReferences;
        this.externalForeignKeyReferences = externalForeignKeyReferences;
    }

}